### ISSUE TITLE
dump_router6: allow specification of exact source address

### ISSUE THREAD

**Issue by robbat2** [vanhauser-thc/thc-ipv6#11]
If an interface has multiple addresses (esp link-local), it can be useful to specify the exact source address to use when sending the IPV6 Router Solicitation.

Please add a way to specify said source address.

**Comment by vanhauser-thc** [comment]
why would that make a difference which link local address is used for a router solicitation?

**Comment by robbat2** [comment]
If the router has a restrictive client list (see radvd's `clients` option), and sends unicast RAs in response to Router Solicitation, then it's useful to specify the source address (on the restrictive client list vs not).

**Comment by vanhauser-thc** [comment]
that sounds like a pretty dumb option in radvd :)

everybody can see the router announcement, so it would only make sense if the router would not send an RA, and only reply directly to a solicitating client.

but if that would be implemented, then the lifetime counter could not work anymore and the router would be remove from the clients after 18 hours ...

I added the feature, just a few lines of code.

**Comment by robbat2** [comment]
https://tools.ietf.org/html/rfc7772#section-5.1 says that routers should support unicast responses should be supported, so not everybody sees the RA in that case.

Thanks for implementing :-).
