### ISSUE TITLE
Plase add support for openssl 1.1

### ISSUE THREAD

**Issue by samueloph** [vanhauser-thc/thc-ipv6#13]
While building thc-ipv6 3.2:

thc-ipv6-lib.c: In function ‘thc_generate_key’:
thc-ipv6-lib.c:3115:3: warning: ‘RSA_generate_key’ is deprecated [-Wdeprecated-declarations]
   if ((key->rsa = RSA_generate_key(key_len, 65535, NULL, NULL)) == NULL) {
   ^~
In file included from /usr/include/openssl/rsa.h:13:0,
                 from thc-ipv6-lib.c:46:
/usr/include/openssl/rsa.h:193:1: note: declared here
 DEPRECATEDIN_0_9_8(RSA *RSA_generate_key(int bits, unsigned long e, void
 ^

**Comment by samueloph** [comment]
If somebody sets up a patch, i can fit 3.2 into the next Debian stable, our final upload date is 25th January, if i don't fix this until them, the next stable will have 3.0.

Worst case scenario, i can do a backported package of 3.2 for Stretch.

**Comment by vanhauser-thc** [comment]
I am not sure I have time until then. I hope, but no guarantees :(

**Comment by vanhauser-thc** [comment]
patch was actually easy, had done the same previously for hydra already
