### ISSUE TITLE
covert_send6d unable to receive file above 1 packet in size

### ISSUE THREAD

**Issue by mculig** [vanhauser-thc/thc-ipv6#16]
I've had this problem both in the versions available on Kali Linux by default, and installable on Debian Linux through the default repositories available at install.
I've reviewed your code and determined the problem to lie on line 78.
The while loop on said line should read:
`while (rlen > 0 && end == 0 && dlen > pos && done == 0)`
instead of:
`while (rlen > 0 && end == 0 && dlen >= pos && done == 0)`
When dlen=pos, pos is at the start of the icmp, resulting in ptr[pos] being 0x80, the code for an ICMP echo request. 
The condition:
`else if (ptr[pos] > 0x1f)` 
evaluates as true (0x80 > 0x1f), causing the function to return without incrementing seq.

**Comment by vanhauser-thc** [comment]
I fixed the >= to > in the repository.
I am swamped with work at the moment - can you please test that everything still works?

**Comment by mculig** [comment]
Cloned and ran make on my Debian test VM.
When running covert_send6d with:
`covert_send6d eth0 file.out`
I receive the file properly now.

**Comment by vanhauser-thc** [comment]
thanks!
