### ISSUE TITLE
3.2 has non-free files

### ISSUE THREAD

**Issue by samueloph** [vanhauser-thc/thc-ipv6#19]
Hello, i'm currently working on packaging the last release of thc-ipv6 on Debian (which should be downstreamed to Ubuntu and Kali) and i stumbled upon a problem.

It looks like all the files inside rfc/ are non-free, please have a look at these links[1][2] and consider the removal of the rfc folder.

If you're willing to remove the rfcs from the source code and make a new release without them, i can wait for it and package this new release instead of 3.2. If not, i can do a +dfsg.n[4] release, removing the rfc folder.

Thanks.

[1]https://wiki.debian.org/NonFreeIETFDocuments
[2]http://josefsson.org/bcp78broken/
[3]https://lintian.debian.org/tags/license-problem-non-free-RFC.html
[4]https://wiki.debian.org/DebianMentorsFaq#What_does_.2BIBw-dfsg.2BIB0_or_.2BIBw-ds.2BIB0_in_the_version_string_mean.3F

**Comment by vanhauser-thc** [comment]
who would have thought that RFCs are non-free? never came to my mind at least.
I will remove it from the repository, but not make a new release yet :)

**Comment by samueloph** [comment]
@vanhauser-thc i must confess i was kinda impressed with this discovery.

Thanks for the removal, i will then prepare a dfsg release for 3.2.
