### ISSUE TITLE
Help !! Compilation of connsplit6 failed, you have to install libnetfilter-queue-dev for this!

### ISSUE THREAD

**Issue by cssxn** [vanhauser-thc/thc-ipv6#26]
I'm sure ` libnetfilter-queue-dev` was installed.

**Ubuntu 16.04 TLS x64**

```
gcc -Ofast -falign-functions -falign-jumps -falign-loops -falign-labels -freorder-blocks -freorder-blocks-and-partition -D_HAVE_SSL  -o fragrouter6 fragrouter6.c thc-ipv6-lib.o -lpcap -lssl -lcrypto -lnetfilter_queue || /bin/echo -e "\nCompilation of fragrouter6 failed, you have to install libnetfilter-queue-dev for this!\n"
gcc -Ofast -falign-functions -falign-jumps -falign-loops -falign-labels -freorder-blocks -freorder-blocks-and-partition -D_HAVE_SSL  -o connsplit6 connsplit6.c thc-ipv6-lib.o -lpcap -lssl -lcrypto -lnetfilter_queue || /bin/echo -e "\nCompilation of connsplit6 failed, you have to install libnetfilter-queue-dev for this!\n"

```

**Comment by vanhauser-thc** [comment]
Hi,

well ... it did not compile? why? what were the errors? and did you verify that libnetfilter-queue-dev is installed? sorry, my crystalball is not working today ...

**Comment by cssxn** [comment]
@vanhauser-thc 
no, I  installed libnetfilter-queue-dev and other requirements. when I execute `make all`

The error occurs

```
nCompilation of connsplit6 failed, you have to install libnetfilter-queue-dev for this!
```

**Comment by vanhauser-thc** [comment]
Is anything else reported as error before the message?
My guess is it has compiled.
check please if a connsplit6 binary is present in the directory.

**Comment by vanhauser-thc** [comment]
so did you check if connsplit6 in fact really compiled?

**Comment by cssxn** [comment]
@vanhauser-thc  I record a video for this issue 

https://asciinema.org/a/vfO6TfFqCG64bACRxefI1XbXh

**Comment by vanhauser-thc** [comment]
you are new to Linux right?
your output showed that it cleanly compiled and is there.
just type "make install" and then "connsplit6 -h"
