### ISSUE TITLE
Missing Error Check in function BN_set_word()

### ISSUE THREAD

**Issue by lc3412** [vanhauser-thc/thc-ipv6#29]
Function BN_set_word() returns 1 on success, 0 otherwise. However , the return value of function BN_set_word() in thc-ipv6/thc-ipv6-lib.c is not checked. See the following code:

line:  3210
https://github.com/vanhauser-thc/thc-ipv6/blob/011376c71cb18ab450bfe5d264f130163a2f51ab/thc-ipv6-lib.c#L3203-L3219

We find the return value of this call been checked in openssl project with the version of openssl 1.1.2.
Such as in openssl/crypto folder

Ref : https://github.com/openssl/openssl/blob/0db957dbbcf6a432086ab913378c23636d8c374c/crypto/asn1/a_object.c#L106
```c
106:        bl = BN_new();
107:        if (bl == NULL || !BN_set_word(bl, l))
108:            goto err;
```
Chi Li, Zuxing Gu, Jiecheng Wu

**Comment by vanhauser-thc** [comment]
fixed, thanks
