### ISSUE TITLE
Which part is interface?

### ISSUE THREAD

**Issue by Jan3kk** [vanhauser-thc/thc-ipv6#32]
Simple question: for example i have ipv6 like this: 2a21:117f:452:d00:fc0c:ab47:5a6e:6969
and don't know which part of it is interface and which part of it is destination.
Can you please point it out so I can just learn from a single example. Thanks !

**Comment by Jan3kk** [comment]
Never mind, I just realised how dumb I am.

**Comment by vanhauser-thc** [comment]
everybody is learning
