### ISSUE TITLE
Install error - make

### ISSUE THREAD

**Issue by The-SamminAter** [vanhauser-thc/thc-ipv6#35]
```
$ make
gcc -O3 -march=native -flto -falign-functions -falign-jumps -falign-loops -falign-labels -freorder-blocks -freorder-blocks-and-partition -D_HAVE_SSL   -c -o thc-ipv6-lib.o thc-ipv6-lib.c
clang: error: unknown argument: '-freorder-blocks-and-partition'
clang: warning: optimization flag '-falign-functions' is not supported [-Wignored-optimization-argument]
clang: warning: optimization flag '-falign-jumps' is not supported [-Wignored-optimization-argument]
clang: warning: optimization flag '-falign-loops' is not supported [-Wignored-optimization-argument]
clang: warning: optimization flag '-falign-labels' is not supported [-Wignored-optimization-argument]
clang: warning: optimization flag '-freorder-blocks' is not supported [-Wignored-optimization-argument]
make: *** [thc-ipv6-lib.o] Error 1```

**Comment by vanhauser-thc** [comment]
gcc points to clang for you? weird.

I removed the unknown argument for clang, and CC and CLAGS are now honored

**Comment by The-SamminAter** [comment]
$ make
cc -O3 -march=native -flto -falign-functions -falign-jumps -falign-loops -falign-labels -freorder-blocks -D_HAVE_SSL   -c -o thc-ipv6-lib.o thc-ipv6-lib.c
clang: warning: optimization flag '-falign-functions' is not supported [-Wignored-optimization-argument]
clang: warning: optimization flag '-falign-jumps' is not supported [-Wignored-optimization-argument]
clang: warning: optimization flag '-falign-loops' is not supported [-Wignored-optimization-argument]
clang: warning: optimization flag '-falign-labels' is not supported [-Wignored-optimization-argument]
clang: warning: optimization flag '-freorder-blocks' is not supported [-Wignored-optimization-argument]
thc-ipv6-lib.c:20:10: fatal error: 'netpacket/packet.h' file not found
#include <netpacket/packet.h>
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [thc-ipv6-lib.o] Error 1

@vanhauser-thc, I have a new error

**Comment by vanhauser-thc** [comment]
on what platform are you?

**Comment by The-SamminAter** [comment]
macOS 10.12.6 (Sierra)
