### ISSUE TITLE
Segmentation fault on ARM

### ISSUE THREAD

**Issue by BlackyFox** [vanhauser-thc/thc-ipv6#37]
Hi, 

First of all, thanks for this framework, it's really great!
However, I was trying to use it on a Raspberry Pi 4 and it didn't work.
Compiling was fine, no errors outputed, but I have some segmentation fault while executing dump_router6, detect-new-ip6, implementation6, fake_router6 or dos-new-ip6.

Is there something I have to modified before compiling the code for ARM?
I also tried on a clean NetHunter install on a OnePlus 6T and 3 and got the same result (that's why I assume it might be linked to ARM).

Thanks.

**Comment by vanhauser-thc** [comment]
I havent tried it on arm, so dunno. and I dont have one at hand to just try it.
have you tried the one from the distro repository? it is e.g. in debian and kali. (the commands have been renamed with atk6-... I think)

**Comment by BlackyFox** [comment]
Yes, I tried on the nethunter the kali repo version, but without any luck. 
Same with the rapsberry. 
I'll try to do a bit of debugging and update my findings here.

**Comment by vanhauser-thc** [comment]
I did some fixes to the code, can you please retest?

**Comment by illustris** [comment]
Tested fake_router6 from thc-ipv6 3.8 on nixos on a pi 3 (aarch64). No segfaults.
