### ISSUE TITLE
passive_discovery6 Segmentation fault (core dumped) on Ubuntu 20.04

### ISSUE THREAD

**Issue by ScottHogg** [vanhauser-thc/thc-ipv6#38]
Recently I have been experiencing issues running passive_discovery6 on new Ubuntu 20.04.1 systems.
It compiles without errors and I have all of the dependent libraries loaded correctly as I have done for years.
I've tried to update, do a make clean, then do a make all, and make install again, no errors (other than on fuzz_dnsps6 & fuzz_dhcpc6, connect6).
Other THC tools seem to work fine, but when I run passive_discovery (and detect-new-ip6), it get this.

# passive_discovery6 ens33
Started IPv6 passive system detection (Press Control-C to end) ...
Segmentation fault (core dumped)
# detect-new-ip6 ens33
Started ICMP6 DAD detection (Press Control-C to end) ...
Segmentation fault (core dumped)
# uname -a
Linux ubuntu2004 5.4.0-54-generic #60-Ubuntu SMP Fri Nov 6 10:37:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by vanhauser-thc** [comment]
looking at the cores I wonder how these tools ever worked. weird.

fixed it, please test.

**Comment by ScottHogg** [comment]
I was able to download the corrected version and it works great!  passive_discovery6 and detect-new-ip6 work now.  Thank you very much.
