### ISSUE TITLE
Install Error - Make

### ISSUE THREAD

**Issue by devilo001** [vanhauser-thc/thc-ipv6#4]
When trying to install on ubuntu 32-bit system recieving error message
`make
gcc -O2 -D_HAVE_SSL   -c -o thc-ipv6-lib.o thc-ipv6-lib.c
thc-ipv6-lib.c:40:18: fatal error: pcap.h: No such file or directory
compilation terminated.
<builtin>: recipe for target 'thc-ipv6-lib.o' failed
make: *** [thc-ipv6-lib.o] Error 1
`

**Comment by vanhauser-thc** [comment]
:)
