### ISSUE TITLE
SLAAC attack?

### ISSUE THREAD

**Issue by mrbluecoat** [vanhauser-thc/thc-ipv6#45]
Can you perform a SLAAC attack with thc-ipv6?

**Comment by mrbluecoat** [comment]
Possibly related: https://github.com/CiscoCXSecurity/suddensix/pull/2

**Comment by mrbluecoat** [comment]
Appears to be most recent attempt: https://github.com/vdot0x23/suddensix/commit/001d9949b8421989abbc0b92cfc6d49581cc0009#diff-7c46577acf4b7348bf1b1899b8f075eb0ebc766d57b29db1a85546101bae0fe3

**Comment by vanhauser-thc** [comment]
yes, tool is fakerouter26

**Comment by mrbluecoat** [comment]
Sorry to revisit the topic @vanhauser-thc, but I'm stuck and was hoping you could point me in the right direction. I've installed fakerouter26 and I believe it's working:

```
DEBIAN_FRONTEND=noninteractive apt install -y iptables iptables-persistent
update-alternatives --set iptables /usr/sbin/iptables-legacy
update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy

echo "net.ipv4.ip_forward=1" >> /etc/sysctl.d/local.conf
echo "net.ipv6.conf.all.forwarding=1" >> /etc/sysctl.d/local.conf
sysctl -p /etc/sysctl.d/local.conf

apt -t bullseye-backports install -y thc-ipv6
ip6tables -I OUTPUT -p icmpv6 --icmpv6-type redirect -j DROP
atk6-fake_router26 -E Oo -A 2001:db8::00/64 -D 2001:db8::1 eth0
```

I have a Windows 10 machine on the network that picks up the new IPv6 address and I can ping the machine running fake_router26. However, it doesn't use the DNS server on the fake_router26 machine. I've set up [DNS64](https://coredns.io/plugins/dns64/) and [NAT64](https://www.jool.mx/en/) but for some reason the Windows machine isn't autoconfiguring itself to use the DNS server provided by the fake_router26 machine. Do I need to set up a route or am I missing another step?

[Rob VandenBrink](https://isc.sans.edu/diary/No+IPv6%3F++Challenge+Accepted%21+%28Part+1%29/22820) described it best:

> fake_router26 and fake_router6 are the "go to" Man in the Middle attack tools for IPv6 - these allow you to stand up a default router for IPv6, which will be prefered over existing IPv4 routers.  Note that you need to set up a mechanism to forward IPv6 packets.  This means you need to enable IPv6 forwarding, then either tunnel IPv6 outbound, usually to an internet gateway, or nat/proxy the IPv6 packets back to IPv4 (which you then forward to the "real" IPv4 router).  What this means is that there's some thought and preparation required to mount this attack.  
>
> Mounting an IPv6 Man in the Middle attack is as simple as: "fake_router6 eth0  BAD1::00/64" (the last parameter is the network - either your "fake" IPv6 network, or your customer's real IPv6 network).  Note that you then have to do the other half - send the victim stations' packets on to their destination

**Comment by vanhauser-thc** [comment]
My guess is windows does not support dns from a RA. If it does maybe I did implement it incomplete

**Comment by mrbluecoat** [comment]
Is fake_router26 providing DHCPv6 or should I install another tool for that?

For example, https://blog.fox-it.com/2018/01/11/mitm6-compromising-ipv4-networks-via-ipv6/ says:

> mitm6 will reply to those DHCPv6 requests, assigning the victim an IPv6 address within the link-local range. While in an actual IPv6 network these addresses are auto-assigned by the hosts themselves and do not need to be configured by a DHCP server, this gives us the opportunity to set the attackers IP as the default IPv6 DNS server for the victims. It should be noted that mitm6 currently only targets Windows based operating systems, since other operating systems like macOS and Linux do not use DHCPv6 for DNS server assignment.

**Comment by mrbluecoat** [comment]
never mind, fake_dhcps6 is what I wanted
