### ISSUE TITLE
For a good cause... (not use my ipv6 DNS)

### ISSUE THREAD

**Issue by gianfelicevincenzo** [vanhauser-thc/thc-ipv6#48]
Hi @vanhauser-thc. I'd like to ask you a question before I go crazy. I have a home router that kind of sucks. So I created another router with **DNS**/**DHCP** server for **ads blocking**. All devices work except **Android**: that is, they don't use my DNS ip that I provide them via my server. Maybe I even figured out the cause. In the home router it is possible to disable only the DHCP (ipv4) but not the ipv6 one...consequently, I think android gives precedence to the ipv6 address instead of the ipv4. The question is'. With this tool, is it possible to "fool" the devices and pass them the ipv6 address of my DHCP router (a kind of **arpspoof**)?

Thank you

**Comment by N3S3** [comment]
![1000004786](https://github.com/vanhauser-thc/thc-ipv6/assets/68975029/5678beab-e63a-48bf-91f8-7559ed7d93fe)

here... this IPv6 is trying to login into my Hotmail....just try all the stuff you ever wanted with this address....🤣

**Comment by vanhauser-thc** [comment]
you could fake_dhcp6s to run your own dhcpv6 server. but it could also be that android has a predefined dns server that you would need to disable somehow first. dunno. not using android sorry
