### ISSUE TITLE
Getting compile error on a fresh install on raspberry pi

### ISSUE THREAD

**Issue by krunal7558** [vanhauser-thc/thc-ipv6#5]
pi@dev-pi:~ $ uname -a
Linux dev-pi 4.4.21-v7+ #911 SMP Thu Sep 15 14:22:38 BST 2016 armv7l GNU/Linux
pi@dev-pi:~ $
pi@dev-pi:~ $
pi@dev-pi:~ $
pi@dev-pi:~ $ cd ipv6toolkit-v2.0/
pi@dev-pi:~/ipv6toolkit-v2.0 $ sudo make install
gcc  -Wall -c -o libipv6.o tools/libipv6.c
/usr/lib/gcc/arm-linux-gnueabihf/4.9/cc1: symbol lookup error: /usr/lib/arm-linux-gnueabihf/libisl.so.10: undefined symbol: _aff_list_get_ctx
GNUmakefile:110: recipe for target 'libipv6.o' failed
make: **\* [libipv6.o] Error 1
pi@dev-pi:~/ipv6toolkit-v2.0 $ cd ..
pi@dev-pi:~ $ cd thc-ipv6/
pi@dev-pi:~/thc-ipv6 $ sudo make install
gcc -Ofast -falign-functions -falign-jumps -falign-loops -falign-labels -freorder-blocks -freorder-blocks-and-partition -D_HAVE_SSL   -c -o thc-ipv6-lib.o thc-ipv6-lib.c
/usr/lib/gcc/arm-linux-gnueabihf/4.9/cc1: symbol lookup error: /usr/lib/arm-linux-gnueabihf/libisl.so.10: undefined symbol: _aff_list_get_ctx
<builtin>: recipe for target 'thc-ipv6-lib.o' failed
make: **\* [thc-ipv6-lib.o] Error 1
pi@dev-pi:~/thc-ipv6 $
pi@dev-pi:~/thc-ipv6 $ sudo apt-get install libpcap-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
libpcap-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
pi@dev-pi:~/thc-ipv6 $ sudo apt-get install libnetfilter-queue-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
libnetfilter-queue-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
pi@dev-pi:~/thc-ipv6 $ sudo apt-get install libssl-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
libssl-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
pi@dev-pi:~/thc-ipv6 $ ^C
pi@dev-pi:~/thc-ipv6 $ ls -al /usr/lib/arm-linux-gnueabihf/libisl.*
lrwxrwxrwx 1 root root     16 Jul  1  2014 /usr/lib/arm-linux-gnueabihf/libisl.so.10 -> libisl.so.10.2.2
-rw-r--r-- 1 root root 938496 Jul  1  2014 /usr/lib/arm-linux-gnueabihf/libisl.so.10.2.2

**Comment by vanhauser-thc** [comment]
first - why did you post the compile error in ipv6toolkit-v2.0 ? this has nothing to do with thc-ipv6 :)

Then:
gcc -Ofast -falign-functions -falign-jumps -falign-loops -falign-labels -freorder-blocks -freorder-blocks-and-partition -D_HAVE_SSL -c -o thc-ipv6-lib.o thc-ipv6-lib.c
/usr/lib/gcc/arm-linux-gnueabihf/4.9/cc1: symbol lookup error: /usr/lib/arm-linux-gnueabihf/libisl.so.10: undefined symbol: _aff_list_get_ctx
: recipe for target 'thc-ipv6-lib.o' failed

this is weird. libisl? thc-ipv6 (nor ipv6toolkit) link against libisl. as you can see on the command line.

Could it be that your gcc installation is broken? have you tried to compile something else? My guess would be that you can not compile anything.

**Comment by krunal7558** [comment]
I haven't tried all but I got same error when compiling ipv6toolkit and thc-ipv6. I will see I can install another fresh raspbian and compile there. 
Yes you are right I could not compile anything. 
Thnx for response.
