### ISSUE TITLE
'thcping6' terminated by signal SIGILL (Illegal instruction)

### ISSUE THREAD

**Issue by D3vil0p3r** [vanhauser-thc/thc-ipv6#52]
I am using Arch Linux and I installed the tool by Arch repository.

When I run `thcping6`, I get:
```
'thcping6' terminated by signal SIGILL (Illegal instruction)
```

**Comment by christian-heusel** [comment]
https://gitlab.archlinux.org/archlinux/packaging/packages/thc-ipv6/-/issues/1

**Comment by vanhauser-thc** [comment]
> https://gitlab.archlinux.org/archlinux/packaging/packages/thc-ipv6/-/issues/1

thanks, that was helpful. changed the makefile.
